proto: migrate to buf
authzed/authzed-py pull request #6
Opened 2021-06-21 14:42 UTC by jzelinskie

Signed-off-by: Jimmy Zelinskie <jimmy@zelinskie.com>

2021-06-25 16:41 UTC, jakedt reviewed
Why don't we have a run tests workflow?

2021-06-28 19:25 UTC, jakedt requested changes

2021-06-28 19:50 UTC, jzelinskie commented on arrakisclient/aio.py
> +            if use_content_change_check:
This is just a sync of the last internal version. Let's clean it up after the protos changes get in.

2021-06-28 19:53 UTC, jakedt approved these changes

2021-06-28 19:53 UTC, merged